### ISSUE TITLE
Add more snapshot tests

### ISSUE THREAD

**Issue by FelixCCWork** [Felix-CodingClimber/DotNetElements.Core.Result#3]
Improve current and add additional snapshot tests

**Comment by Felix-CodingClimber** [comment]
Integrate verify in github actions

Getting .received in output on GitHub Actions
Use a [if: failure()](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#failure) condition to upload any *.received.* files if the build fails.

```
- name: Upload Test Results
  if: failure()
  uses: actions/upload-artifact@v4
  with:
    name: verify-test-results
    path: |
      **/*.received.*
```
